### ISSUE TITLE
pypi packaging problems

### ISSUE THREAD

**Issue by ser** [mbr/visitor#1]
Hi, I am packager for arch linux, two issues:

1) No license file in pypi package
2) chmod 600, you know :)

**Comment by mbr** [comment]
I'll fix the LICENSE issue and the new release will also fix the permission issues.

**Comment by mbr** [comment]
Done. Try `>=0.4.3`.

**Comment by ser** [comment]
Thanks for fixing flask-debug, but visitor is not fixed yet :)

**Comment by mbr** [comment]
Should work now.

**Comment by ser** [comment]
Sorry, still no LICENSE file...

**Comment by mbr** [comment]
Missing MANIFEST.in. I really wish LICENSE would get automatically included like README.rst.

**Comment by mbr** [comment]
Fixed in 0.1.2.

**Comment by ser** [comment]
It works, thanks for your patience :+1:
